Collections:
- Name: Swin
  Paper:
    Title: 'Swin transformer: Hierarchical vision transformer using shifted windows'
    URL: https://arxiv.org/abs/2103.14030
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/swin.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/swin_t_p4_w7_coco_256x192.py
  In Collection: Swin
  Metadata:
    Architecture: &id001
    - SimpleBaseline2D
    - Swin
    Training Data: COCO
  Name: topdown_heatmap_swin_t_p4_w7_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.724
      AP@0.5: 0.901
      AP@0.75: 0.806
      AR: 0.782
      AR@0.5: 0.94
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/swin/swin_t_p4_w7_coco_256x192-eaefe010_20220503.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/swin_b_p4_w7_coco_256x192.py
  In Collection: Swin
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_swin_b_p4_w7_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.729
      AP@0.5: 0.899
      AP@0.75: 0.808
      AR: 0.786
      AR@0.5: 0.939
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/swin/swin_b_p4_w7_coco_256x192-5fa9d10f_20220503.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/swin_b_p4_w7_coco_384x288.py
  In Collection: Swin
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_swin_b_p4_w7_coco_384x288
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.749
      AP@0.5: 0.905
      AP@0.75: 0.818
      AR: 0.803
      AR@0.5: 0.942
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/swin/swin_b_p4_w7_coco_384x288-3a570e2e_20220503.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/swin_b_p4_w7_fpn_coco_256x192.py
  In Collection: Swin
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_swin_b_p4_w7_fpn_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.731
      AP@0.5: 0.9
      AP@0.75: 0.809
      AR: 0.788
      AR@0.5: 0.941
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/swin/swin_b_p4_w7_fpn_coco_256x192-46712568_20220503.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/swin_b_p4_w7_fpn_coco_256x192.py
  In Collection: Swin
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: topdown_heatmap_swin_b_p4_w7_fpn_coco_256x192
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.751
      AP@0.5: 0.906
      AP@0.75: 0.822
      AR: 0.805
      AR@0.5: 0.943
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/swin/swin_b_p4_w7_fpn_coco_384x288-36c3de00_20220503.pth
